FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:20-alpine AS production

WORKDIR /app

COPY package.json package-lock.json ./

RUN yarn install --production

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main"]